### ISSUE TITLE
Analytics panel does not look finished

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#105]
Compared to the [previous version](http://adaptiveconsulting.github.io/ReactiveTraderJS/):
 - no legend on the chat (x axis should show the time) 
 - the chart was green when > 0 and red when <= 0
 - please keep the style as close as possible to the old one (no black line / panel delimiter, same section titles, etc)
 - the bars at the bottom look huge when there are only a few positions
 - previously the bars where looking red / green following the same pattern (red < 0, green > 0)
 - positions notional (in black) overlays with the labels. The notional are normally displayed when you mouse over the corresponding bars (see link to previous version).
 --> it looks like the control used to display positions does not work for our use case, could we just implement it in html/css like it was before (it works fine and looks a lot better)
 - Format 'Profit & Loss' total with thousand separators (or even shorten to "1.3m"/"555k"

![image](https://cloud.githubusercontent.com/assets/1256913/11964681/3ea1e536-a8e7-11e5-9d8d-d9a9658b4130.png)

the old verion looks a lot better, could we try to replicate the styles?

![image](https://cloud.githubusercontent.com/assets/1256913/11964660/2172f108-a8e7-11e5-8cb5-cd72fa97aa4f.png)

**Comment by KeithWoods** [comment]
still not looking correct

![image](https://cloud.githubusercontent.com/assets/2853674/14381997/5ffb5f60-fd82-11e5-912a-ac2da82652b6.png)

The problem here are the styles need a complete re-work. I'm going to group this issues with a style label so we can trash the existing styles, clean them up, then knock off these issues.

**Comment by KeithWoods** [comment]
relates to #106
