### ISSUE TITLE
Crossed RFQ pricing

### ISSUE THREAD

**Issue by qooroo** [AdaptiveConsulting/ReactiveTraderCloud#1051]
![image](https://user-images.githubusercontent.com/1429601/57928772-894f6a00-78a9-11e9-8921-f740397967c7.png)

RFQ pricer should not give crossed prices.

**Comment by mbehery85** [comment]
This has been tested against the latest release and this issue does now seem to be resolved.

Checked against the variables displayed in the screen shot and also other CCY pairs and different amounts and these too look correct.

Thanks
