### ISSUE TITLE
How to just start

### ISSUE THREAD

**Issue by joyanta** [AdaptiveConsulting/ReactiveTraderCloud#1070]
Hi, 
I am using this project to learn very advanced coding which i have not seen so far in my career. 

I have downloaded the code, built it but when i run it with the launcher being the main project, it states 'Trying to connect to broker...and fails at point Log.Error(exception, "Connection Failed for url " + uri) in class BrokerConnection.

I suspect I am not running everything.

It is at all possible to provide some docs for coders like me who clearly is not as advanced. 

Just a couple of steps for me to just run this.

**Comment by lidia-adaptive** [comment]
Hi Joyanta,

Sorry to hear you were struggling, we are in the process of updating documentation but unfortunately we do not provide individual support for running the app.

Kind regards,
Lidia
