### ISSUE TITLE
Reduce Build times

### ISSUE THREAD

**Issue by raybooysen** [AdaptiveConsulting/ReactiveTraderCloud#126]
Current build times for the client are > 6 minutes.  

Some thoughts:
1) This is very long
2) Do we need the entire container infrastructure just to build, run unit tests?
3) Can we split out another build that is just the day to day dev builds so we get quick feedback?
4) Surely CircleCI allows us to build on pre-ready machines (ones with npm and node already installed)

**Comment by tdeheurles** [comment]
This PR address this problem: https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/254
