### ISSUE TITLE
Client should be able to connect to the cloud

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#133]
It would be a lot easier for client side developers to be able to run the client and connect it to the services running on the cloud.

Tasks:
 - configure CORS
 - update the documentation (people interested only by the client should know that this is available)
 - add a npm command to launch the client and connect it to the cloud

**Comment by KeithWoods** [comment]
`npm start` (the default use case) should default the backend to the cloud. It should be an edge case to point to your local environment. 

I suggest we have these targets:
* `npm run dev:local`  
* `npm run dev:cloud` 

Point `npm start` to `npm run dev:cloud`

**Comment by tdeheurles** [comment]
@keith these changes will impact the automated deployment. Just let me know if/when you add it please.

**Comment by KeithWoods** [comment]
@bnwan is this now done?

**Comment by bnwan** [comment]
@KeithWoods this has been merge into the dev branch
