### ISSUE TITLE
dev server problems

### ISSUE THREAD

**Issue by DimitarChristoff** [AdaptiveConsulting/ReactiveTraderCloud#149]
left overnight, client disconnected. upon reconnect, pricing service was not picked up. killing pricing did not unsubscribe. starting a new p2 got picked up by status but no prices ticked. killing any of the pricing services did not work, subsequent `exit` command crashed the server.

**Comment by qooroo** [comment]
Pricing is not reliably up, this is hindering frontend dev work.

**Comment by qooroo** [comment]
This seems to be resolved after upgrading crossbar to v0.13.2-trusty

This guy seems to have a similar issue but is also using an older version of crossbar:

http://stackoverflow.com/questions/31777490/autobahn-error-no-callee-registered-for-procedure-after-long-period-of-inactiv

**Comment by qooroo** [comment]
Closing for now, will reopen if it occurs again.

**Comment by qooroo** [comment]
Seen again in dev today with build 1268, nothing obvious in the client and server logs.

The server method for subscribing to client `getPriceStream` requests is not being hit.

[ClientLog.txt](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/files/270226/ClientLog.txt)
[ServerLog.txt](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/files/270225/ServerLog.txt)

**Comment by qooroo** [comment]
#396 will resolve this
