### ISSUE TITLE
I am able to submit a trade even when the error Notional value 'Max exceeded' is displayed

### ISSUE THREAD

**Issue by TejavardhanP** [AdaptiveConsulting/ReactiveTraderCloud#1672]
Ignore this if the 'Demo' version is not latest version nor a known issue.
![image](https://user-images.githubusercontent.com/73316911/96936343-c0be3f00-14bd-11eb-8ce2-754bae0caa16.png)

**Comment by garyadaptive** [comment]
Thanks for reporting this. This issue was fixed in release v1.6.0.
