### ISSUE TITLE
When we uncheck and re-select a filter value, the 'select all' check box is not being selected, because of which the header is showing the filtered value in the header.

### ISSUE THREAD

**Issue by TejavardhanP** [AdaptiveConsulting/ReactiveTraderCloud#1673]
Steps:
1) Make sure 'Select All' is preselected.
2) Deselect (or uncheck) one of the selected value (ex: WMO) ---- output: The 'Select All' checkbox is deselected. 'Trader' is displayed in header i.e beside filter icon.
3) Reselect WMO.... check mark is not defaulted in 'Select All'  and the filter 'Trader' is still showing.

![image](https://user-images.githubusercontent.com/73316911/96936762-94ef8900-14be-11eb-83ab-16861f265039.png)

**Comment by garyadaptive** [comment]
Thanks! The blotter component is currently undergoing a rewrite, which will include a number of fixes and enhancements.
