### ISSUE TITLE
When we uncheck the 'Select All' in Trader column, the full list of trades are still showing.

### ISSUE THREAD

**Issue by TejavardhanP** [AdaptiveConsulting/ReactiveTraderCloud#1676]
When we uncheck 1 or 2 values of traders, the corresponding rows are disappearing. where as if we uncheck 'Select All', the behaviour is not same as above. Its showing all the records.
![image](https://user-images.githubusercontent.com/73316911/96937684-a0dc4a80-14c0-11eb-967c-e711b9c8e099.png)

**Comment by Mark-Adaptive** [comment]
How do I access the trader column?

**Comment by TejavardhanP** [comment]
As I have done exploratory testing, I am not sure about the requirement. i.e if the Trader column is a mandatory to display. Logically it has to display. And it will be a very very rare case where user deselects all checkboxes.
I raised this based on the behaviour of "checkbox selection" vs "rows to be displayed".
I am closing this issue considering that deselecting 'Select All' checkbox should not do anything.
