### ISSUE TITLE
Possible defect: when i filter records with 'Rejected' status, its showing wrong count in the text at the bottom of the panel.

### ISSUE THREAD

**Issue by TejavardhanP** [AdaptiveConsulting/ReactiveTraderCloud#1677]
Its showing: "Displaying rows 3 of 50".... I feel it should show "Displaying rows 3 of 3" because i applied a filter.
![image](https://user-images.githubusercontent.com/73316911/96938111-78088500-14c1-11eb-8ee8-84c06b513203.png)

**Comment by Mark-Adaptive** [comment]
I believe the second number in 3 of 50 refers to the total number of rows unfiltered and the first number refers to the rows after filtering for the word "rejected."  I don't think this is a bug.

**Comment by TejavardhanP** [comment]
Yes. I agree the second number '50' is the total number of rows. But, as It is showing results of a filter, I thought the total number of rows will also show 3 in place of 50.
I think my defect will be valid if there is paging.
I am closing this issue.
