### ISSUE TITLE
Analytics does not reappear in main view after close in tile mode

### ISSUE THREAD

**Issue by tdeheurles** [AdaptiveConsulting/ReactiveTraderCloud#202]
The `blotter` reappear in the main view after the tile is closed. The behavior is not the same for the `Analytics Tile`

**Comment by LeeCampbell** [comment]
Is this related to #216?

**Comment by tdeheurles** [comment]
I don t think as the first step is to make the analytics as a new window by
clicking on it, so the resolution is ok. It seems that the close event
doesn t trigger anything.

Just supposition here.

Le sam. 12 mars 2016 14:50, Lee Campbell <notifications@github.com> a
écrit :

**Comment by KeithWoods** [comment]
@LeeCampbell I think it's just not finished. #218 / #227 fixes this.
