### ISSUE TITLE
Can't seem blotter on low res displays

### ISSUE THREAD

**Issue by KeithWoods** [AdaptiveConsulting/ReactiveTraderCloud#216]
The blotter doesn't display on small resolutions screens (or small browser windows). 

Looking into this in more details the problem is the flexbox layout for the app isn't correct. The cash tiles don't show scrollbars as their container size is infinite, this pushes the blotter down. 

The styles in general need to be cleaned up, until then this might be a problematic fix.

![image](https://cloud.githubusercontent.com/assets/2853674/13701036/ce0687ee-e77c-11e5-9540-25e49deb0154.png)

**Comment by LeeCampbell** [comment]
FYI, I can reproduce this when just horizontally re-sizing the window (making it narrower). 
First I have it loaded in maximized, then I resize it (and the analytics just disappears). Then when I expand it, the analytics re-appears but the blotter disappears.

### Making narrow looses Analytics
![image](https://cloud.githubusercontent.com/assets/981443/13723323/e2f563d0-e89b-11e5-9df4-23e738e2b288.png)

### Expanding back looses Blotter
![image](https://cloud.githubusercontent.com/assets/981443/13723327/f7ccd82e-e89b-11e5-860a-0066c85ed80a.png)


Chrome 48 Win10

**Comment by luanped** [comment]
Maybe I'm missing something, but adding max-height: 100vh; for the .flex-container seems to solve this issue?

**Comment by raybooysen** [comment]
Does that show it how we discussed offline?
On 21 Mar 2016 17:22, "luanped" <notifications@github.com> wrote:

> Maybe I'm missing something, but adding max-height: 100vh; for the
> .flex-container seems to solve this issue?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AdaptiveConsulting/ReactiveTraderCloud/issues/216#issuecomment-199385935>
>

-- 
 

*This email and any attachments to it may be confidential and are intended 
solely for the use of the individual to whom it is addressed. Any views or 
opinions expressed are solely those of the author and do not necessarily 
represent those of Adaptive Financial Consulting Ltd. *

*If you are not the intended recipient of this email, you must neither take 
any action based upon its contents, not copy nor show it to anyone.*

*Please contact the sender if you believe you have received this email in 
error.*

*Adaptive Financial Consulting Ltd is a company registered in England and 
Wales. Registered number: 08105955. Registered office: 2nd floor, 11 
Leadenhall Street, London EC3 V1LP.*

**Comment by luanped** [comment]
No - had a look at making the blotter area as a % of the screen size rather than fixed (as it looks fine when we have a large display, but takes up close to half the screen when on a smaller display). 

The FixedDataTable we use for the blotter excepts an explicit height in pixels to instantiate the component (hence it is performant at rendering) and currently it's hard coded to be 280px - making it resize as a % of screen size won't be too simple it seems, though we can investigate further?

**Comment by KeithWoods** [comment]
should be address in the style cleanup. relates to #106
