### ISSUE TITLE
Implement pop-outs

### ISSUE THREAD

**Issue by KeithWoods** [AdaptiveConsulting/ReactiveTraderCloud#218]
Spot tiles, analytics and the blotter need to be able to pop out into a new windows. 

Note here was a previous implement of this, however it was removed in recent refactors. It needs to be re-implemented with a clean abstraction, and such an abstraction should work with the openfin integration.

**Comment by LeeCampbell** [comment]
In the mean time, it might be worth removing the redundant popout buttons. Just looks unfinished. Probably better to not have the feature at all, and then add the buttons back in once it is completed properly.

**Comment by KeithWoods** [comment]
#227 ready for review this is pretty much done
