### ISSUE TITLE
The Username button is confusing and appears to do nothing

### ISSUE THREAD

**Issue by LeeCampbell** [AdaptiveConsulting/ReactiveTraderCloud#220]
![image](https://cloud.githubusercontent.com/assets/981443/13723187/6b490196-e898-11e5-9f53-5bd7aee976ee.png)

There is a button in the title bar that appears to do nothing (but confuse me). Is this supposed to be my username? Why the empty brackets afterwards? Any tooltip or visual clue to tell what this artifact is?

It appears to add an item to my navigation stack, meaning I have to navigate _back_ twice to get back to where I came from.

**Comment by KeithWoods** [comment]
#227 will fix this. Additionally the 'Reactive Trader Cloud' text was also a link to / which was removed.
