### ISSUE TITLE
Remove chart (and toggle)

### ISSUE THREAD

**Issue by LeeCampbell** [AdaptiveConsulting/ReactiveTraderCloud#222]
The toggle button to turn on and off a tile's spark lines, while it works, it doesn't act like a toogle button. A toggle button should also visually toggle its own state when toggling.

![image](https://cloud.githubusercontent.com/assets/981443/13723428/cb864b34-e89f-11e5-8680-5f209ee72e69.png)

**Comment by LeeCampbell** [comment]
Also of note, the button shows a Histogram/Bar chart icon, but it is toggling a line chart.

**Comment by KeithWoods** [comment]
Think we should just kill this chart. I think @ferguskeenan would agree based on recent discussions.

**Comment by ferguskeenan** [comment]
Only for done trades
Rejected should need to be dismissed

**Comment by ferguskeenan** [comment]
Remove chart

**Comment by KeithWoods** [comment]
Note: remove the implementation logic from the `SpotTimeModel`

**Comment by KeithWoods** [comment]
@fdore looking at the dev branch looks like there is still code in the model for this. Did you you mean to close this issue?:

https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/dev/src/client/src/ui/spotTile/model/spotTileModel.js#L32

and 

https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/dev/src/client/src/ui/spotTile/model/spotTileModel.js#L178
