### ISSUE TITLE
Once a trade is executed, the tile doesn't automatically flip back to prices

### ISSUE THREAD

**Issue by LeeCampbell** [AdaptiveConsulting/ReactiveTraderCloud#223]
In RT, when you executed a trade, the tile would flip and show a confirmation state. After about 5seconds, it would automatically flip back and show you ticking prices again. This was usefull for performing demos, so you didn't have to go back and click all these small `Done` or `Rejected` links to flip it back.

**Comment by ferguskeenan** [comment]
Only for done trades
Rejected should need to be dismissed
