### ISSUE TITLE
Deployment documentation

### ISSUE THREAD

**Issue by tdeheurles** [AdaptiveConsulting/ReactiveTraderCloud#242]
1) Deployment is hard, because currently only one person knows how to do it
2) We don't have a document on github titled "Deployment instructions for our cloud setup" or something like that (1st step)
3) Ideally this deployment should be done as part of a build.  I.e. wait for build to be complete, hit a button and it's deployed  (2nd step)

Kind of deployment:
- how to push to dockerhub (account/push)
- how to create a cloud cluster from scratch
- how to deploy to this cloud cluster using the dockerhub account

Also:
- how to start a local kubernetes
- how to deploy to that local cluster

**Comment by tdeheurles** [comment]
#### Docker prerequisite
- Install docker toolbox
- Ensure that rt repository was copied with LF
- Ensure that rt repository is in a children folder of your C:\Users (or add a share to the VM)

#### Connection to Gcloud prerequisite
- cd rt repository
- cd deploy/googleCloudEngine
- ./gcloud init
  - copy url to firefox (issue with chrome)
  - select reactive-trader project
  - do not clone repository
- ./getCredentials
- cd ../kubernetes
- ./ns (to control your connection to the cluster)

#### Deployment
- ./deploy mytestenvironment 987

**Comment by odeheurles** [comment]
Once this is properly documented it would be good to have a short blog post explaining that people can create their own google cloud cluster and deploy reactive trader on it

**Comment by tdeheurles** [comment]
Link to the PR: https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/255

**Comment by tdeheurles** [comment]
documentation added: https://github.com/tdeheurles/ReactiveTraderCloud/tree/59fd948a4ad50383430af0f6a149396ff95474b7/docs/deployment
blog post still need to be written

**Comment by tdeheurles** [comment]
new issue for blogpost: https://github.com/AdaptiveConsulting/ReactiveTraderCloud/issues/603
