### ISSUE TITLE
Add Adaptive splash screen

### ISSUE THREAD

**Issue by ferguskeenan** [AdaptiveConsulting/ReactiveTraderCloud#266]
![rt splash](https://cloud.githubusercontent.com/assets/8998351/14646028/e3c6a252-064f-11e6-9a5f-ac7f197431b9.PNG)

**Comment by ferguskeenan** [comment]
This fades out to reveal the app

**Comment by DimitarChristoff** [comment]
should this be read from `package.json?` currently tagged as:
```js
  "version": "2.1.0",
```
