### ISSUE TITLE
Restyle disconnected pop-up to match new font

### ISSUE THREAD

**Issue by ferguskeenan** [AdaptiveConsulting/ReactiveTraderCloud#267]
![expired session warning](https://cloud.githubusercontent.com/assets/8998351/14646184/78207d74-0650-11e6-981e-31ff299210be.PNG)

**Comment by DimitarChristoff** [comment]
this appears to have been fixed. 
![screen shot 2016-04-20 at 14 48 36](https://cloud.githubusercontent.com/assets/119500/14676815/049fa55c-0707-11e6-8e4f-73cd3d484d7c.png)
