### ISSUE TITLE
Blotter re-renders every time there is an update

### ISSUE THREAD

**Issue by ferguskeenan** [AdaptiveConsulting/ReactiveTraderCloud#269]

**Comment by DimitarChristoff** [comment]
seems like something we cannot solve with react fixed-data-table - also, see https://github.com/facebook/fixed-data-table/issues/382 which means big data sets and 50k rows just does not work. 

need to look at replacing the grid component, it does not have a row renderer so every time that data changes - even if it's a single item being updated, it re-renders the whole visible list - something normally avoidable in looped lists via the `key=` property to help react determine what needs to change.

**Comment by DimitarChristoff** [comment]
maybe look at http://griddlegriddle.github.io/Griddle/next/ - new 1.0 api seems very good and extensible and will be out shortly, can be toyed with by using `npm i griddle@alpha`

**Comment by ferguskeenan** [comment]
No required
