### ISSUE TITLE
Upgrade crossbar

### ISSUE THREAD

**Issue by KeithWoods** [AdaptiveConsulting/ReactiveTraderCloud#271]
A newer version of crossbar is out, we should move to this and update our configuration. 

Currently when I run the app I get a message asking to update as my ubuntu machine has a later version. The update is a one line command, however we also need to ensure deployment and documentation is updated.

**Comment by tdeheurles** [comment]
For deployment: [crossbar is installed via crossbar package](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/deploy/docker/build/crossbar/template.install.sh) for now for the deployments. I'm not sure we are already using the same one.

But it point to the fact that the installer should point to a selected version, not just install like it is at the moment.

**Comment by qooroo** [comment]
merged to dev, deployed and tested
