### ISSUE TITLE
Torn out Item has incorrect font

### ISSUE THREAD

**Issue by raybooysen** [AdaptiveConsulting/ReactiveTraderCloud#285]
Torn out:
![image](https://cloud.githubusercontent.com/assets/461957/14704016/099e478c-07b3-11e6-94e2-38f4299974f4.png)

In-browser:
![image](https://cloud.githubusercontent.com/assets/461957/14704032/16147da6-07b3-11e6-8d9c-c713a875f1b4.png)

**Comment by ferguskeenan** [comment]
![tear out font](https://cloud.githubusercontent.com/assets/8998351/14704160/40cdbc9a-07ab-11e6-92ea-c7b3031a1ac1.PNG)
