### ISSUE TITLE
Remove react-popout

### ISSUE THREAD

**Issue by KeithWoods** [AdaptiveConsulting/ReactiveTraderCloud#301]
There are numerous issues with this component:

* approach is incorrect, you don't need a component to open an element. 
* the popout child is bound to a component rendered in a different visual tree
* there are bugs with the onload function (we've forked it)
* seems to be issues with set state (need to verify)

**Comment by DimitarChristoff** [comment]
the `setState` causing an immediate re-render is a bit poor/questionable. this and other reasons like onload firing too early or not firing (depending on url) is why it was sub-classed and the method was re-implemented before.

**Comment by DimitarChristoff** [comment]
not related but a heads up - my PR got cherry-picked and a new version of react-dimensions has been pushed - https://github.com/digidem/react-dimensions/blob/master/index.jsx (now contains window fixes).

maybe local dimensions thing can be deprecated and you can test it with react-dimensions@1.1.0 from npm direct

**Comment by KeithWoods** [comment]
in #303 react-popout has been replaced by `ReactPopoutService`, closing this.
