### ISSUE TITLE
Trading "quickly" causes timeouts

### ISSUE THREAD

**Issue by ferguskeenan** [AdaptiveConsulting/ReactiveTraderCloud#305]
To reproduce, click relatively quickly on multiple tiles - timeout messages appear.

I would not expect this speed of trading to cause such issues.

![rt2 timeouts](https://cloud.githubusercontent.com/assets/8998351/14783263/8ca45b68-0ae6-11e6-8b80-a04009a936bd.PNG)

**Comment by qooroo** [comment]
fixed and deployed to `web-demo`
