### ISSUE TITLE
Unhandled execution behaviour for notionals above int32.max

### ISSUE THREAD

**Issue by qooroo** [AdaptiveConsulting/ReactiveTraderCloud#333]
Currently the backend uses a mix of `int` and `long` for notional. Need to decide on whether we support decimal places or not and keep the notional type consistent.

**Comment by qooroo** [comment]
dependent on whether we support decimals or not #343

**Comment by zeala** [comment]
#343 is fixed now. We do support decimal input (2 dec points) on the front end.

**Comment by qooroo** [comment]
#421 closes this also
