### ISSUE TITLE
Review configuration of app.json

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#339]
Compare with previous reactive trader (https://github.com/AdaptiveConsulting/ReactiveTraderJS/blob/00337478105f1124dfb26cddf5440b173dff07b3/app.json)
 - make sure different environments have different app ids
 - this has to be deployed to nginx as part of the deployement script

**Comment by fdore** [comment]
Config now available here
https://raw.githubusercontent.com/AdaptiveConsulting/ReactiveTraderCloud/dev/src/client/config/openfin/demo.app.json
