### ISSUE TITLE
Create an OpenFin package for the app

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#340]
The installer should be created using the usual OpenFin service:

https://dl.openfin.co/services/download?fileName=<<INSTALLER_FILE_NAME>>&config=<<URL_APP_JSON>>

**Comment by fdore** [comment]
@tdeheurles Here is a question for you.
The app.json needs to contain the application url, which is only known when we deploy the container, as it is based on the environment namespace. We could output the manifest template as part of the build, and then update and deploy the manifest before pushing the container out.
Does that sound reasonable/feasible?
