### ISSUE TITLE
Integrate the new ChartIQ App

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#355]
Seb at OpenFin needs to come back to us with the details

**Comment by Frenchy** [comment]
From Gus Matlis at ChartIQ:

Hi Seb,

I don't think this code needs to change. But I'm not familiar with what adaptive has done on their side. 
Not sure if they've included stx-advanced.html, or whether they've worked with the SDK directly. 
Either way, it should work out of the box by simply replacing the files they now have with the latest; and if they want to take advantage of our new UI, they can look at then new chartiq.html template.

Let me know what domains I should lock the new release to and I will create a new package for them. Or have them send me the current stxKernelOs.js file they are using and I can take a look.

Thanks!

Gus

**Comment by fdore** [comment]
We are currently launching the charting app from the following url http://openfin.chartiq.com/0.5/chartiq-shim.html?symbol=${symbol}&period=${interval}

Here is the code where it is setup:
https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/client/src/system/openFin/openFin.js#L165

**Comment by Frenchy** [comment]
Here is the latest library
[Adaptive-Version 2016-05-10.1.zip](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/files/282407/Adaptive-Version.2016-05-10.1.zip)
.

The details are as follows:
/* File generated on Wed May 25 2016 12:15:44 GMT-0400 (EDT) */
/* Version 2016-05-10.1 */
/* Expires on 2017/06/01 */
/* Locked to domains ["127.0.0.1","localhost","adaptiveconsulting.github.io"] */


Here is a link to the change log:
http://documentation.chartiq.com/tutorial-Changelog.html

**Comment by ferguskeenan** [comment]
Latest version available here: http://demo.chartiq.com/chartiq.html
And the documentation/changelog: http://documentation.chartiq.com/

Please contact dev@chartiq.com to get a version of the library to integrate.

**Comment by ferguskeenan** [comment]
Package available here:
http://license.chartiq.com/packager/download/dbcf5f75-984b-4032-8240-a744f6f95952/Adaptive-Version%20m-2016-12-01.4.1.zip

**Comment by fdore** [comment]
Latest version has been integrated
cf. https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/565
