### ISSUE TITLE
Docking and snapping of spot tiles

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#357]
OpenFin have a script which manages snapping and docking of windows which can be found here: https://github.com/openfin/snap-and-dock

The window manager does not support windows which are resizable, so ideally we should prevent the docking of tiles with the main window (ie. only allow tiles to be docked to each other). We will also need a button on the tiles to undock them (only visible when you mouse over a tear-out window).

We know that there are edge cases that the window management script does not handle, this is fine - we will just have to be aware of them when we do a demo.

**Comment by fdore** [comment]
Spot tiles can now be docked to other tiles.
