### ISSUE TITLE
IE issues

### ISSUE THREAD

**Issue by qooroo** [AdaptiveConsulting/ReactiveTraderCloud#367]
- [x] Console error: `SCRIPT5007: Unable to get property 'contains' of undefined or null reference app.js (4,17460)`
ESP subsequently stops the app: `Event router halted due to previous error [TypeError: Unable to get property 'contains' of undefined or null reference]`

- [x] Tile layout issue:
![image](https://cloud.githubusercontent.com/assets/1429601/15428747/22ea7bf4-1e95-11e6-965a-c9604aa56e1c.png)

- [x] Analytics chart colouring:
![image](https://cloud.githubusercontent.com/assets/1429601/15428763/37c96346-1e95-11e6-85b1-9893213596ed.png)

- [x] PnL / Positions bars not showing in analytics panel

- [ ] Popouts don't work

- [ ] Blotter dates render as NaN
![image](https://cloud.githubusercontent.com/assets/1429601/15429436/de1e01c2-1e98-11e6-9601-d8836f15032f.png)

**Comment by fdore** [comment]
the console error seems related to chartgradient js which I dont think we even use...
