### ISSUE TITLE
Interop issue with ChartIQ

### ISSUE THREAD

**Issue by fdore** [AdaptiveConsulting/ReactiveTraderCloud#390]
ChartIQ has UUIDs being hard coded to the following
["Launcher","reactive-trader-js","reactive-trader-js-staging"].
This causes communication issues with Reactive Trader Cloud, which has different UUID.
#355, #46

**Comment by Frenchy** [comment]
What is the new UUID?

**Comment by fdore** [comment]
Demo env: reactive-trader-cloud-web-demo
Dev env: reactive-trader-cloud-web-dev
Local env: reactive-trader-cloud-local
