### ISSUE TITLE
No price for EURUSD

### ISSUE THREAD

**Issue by fdore** [AdaptiveConsulting/ReactiveTraderCloud#455]
![screen shot 2016-06-29 at 08 43 06](https://cloud.githubusercontent.com/assets/2005635/16444361/91629eea-3dd5-11e6-98f3-ebeacf08ceeb.png)

**Comment by fdore** [comment]
Seems to happen when restarting pricing service

**Comment by qooroo** [comment]
Yeah I'll take a closer look if it happens again
