### ISSUE TITLE
WPF Credit checker integration

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#46]
same story as excel integration, the existing code is there and we should keep the same protocol to not have to rebuild/redeploy the WPF app.

https://github.com/AdaptiveConsulting/ReactiveTraderJS/blob/master/src/ts/OpenFin/OpenFin.ts

**Comment by KeithWoods** [comment]
dependent on #217

**Comment by fdore** [comment]
so it seems that the uuid of RT needs to be reactive-trader-js for both apps to be able to communicate, which is not ideal if we support multiple environments...

**Comment by fdore** [comment]
New version allowing any uuid available here http://adaptiveconsulting.github.io/ReactiveTraderCloud/install/LimitChecker/LimitChecker.application
