### ISSUE TITLE
Consider using React Storybook

### ISSUE THREAD

**Issue by nickytonline** [AdaptiveConsulting/ReactiveTraderCloud#483]
Consider using [React Storybook](https://github.com/kadirahq/react-storybook). It's a great way to develop/design React components.

**Comment by nickytonline** [comment]
@raybooysen, @KeithWoods . This just adds React Storybook to Reactive Trader cloud. There are no stories added to it yet to test out UI components.

**Comment by raybooysen** [comment]
Merged #484, will leave this open until some stories have been added.

**Comment by zeala** [comment]
Storybook and stories have been added. closing this issue
