### ISSUE TITLE
Why WAMP & Crossbar

### ISSUE THREAD

**Issue by promontis** [AdaptiveConsulting/ReactiveTraderCloud#497]
Just listened to the DotNetRocks episode. I'm so curious why you choose for WAMP & Crossbar instead of other messaging platforms, like SignalR and RabbitMQ for example. Saw the wiki entry on this topic, but unfortunately it is only a placeholder. Could you enlighten us :) ?

**Comment by qooroo** [comment]
There's a blog post in the works on this - I'll leave this issue open until we publish that post.

**Comment by promontis** [comment]
Thnx for the explanation @JPWatson! Really helpful! 

Looking back, would you still build everything using crossbar? Or would you use SignalR?

I've also did some searching on the internet... http://tavendo.com/blog/post/is-crossbar-the-future-of-python-web-apps/ is a good post on this subject. 

> WAMP compares to AMQP, and e.g. Crossbar.io compares to RabbitMQ.

Still looking into why WAMP instead of AMQP. I think AMQP is a bit more popular on the web, but I don't mind using a less popular tech if it is better suited. 

Could you guys - having actually used crossbar - give something like a comparison between the two? When would you use crossbar vs the likes of signalr + rabbitmq? Or perhaps WAMP vs AMQP? 

Also, did you look into stateful services? It seems trading system would be really suited. For example, Akka.NET or Azure Service Fabric.

**Comment by JPWatson** [comment]
If we didn't use a broker, I think SignalR would do the job perfectly well. 

AMQP has definitely been around longer. It has a lot more flexibility that we just didn't need for this project and with flexibility comes extra complexity so we went with the simpler option. 
For example, one of the differences is that WAMP has request response out of the box whereas you need to build it yourself with AMQP using correlation ids or some similar mechanism.

We did look briefly at Akka.NET but didn't have time in the end to fully explore it, it's quite a paradigm shift. I think if we do have time to make a Reactive Trader Cloud v2.0, we might try to do something using the Actor model.
