### ISSUE TITLE
Web UI does not work when running locally from Docker (Windows)

### ISSUE THREAD

**Issue by sirockin** [AdaptiveConsulting/ReactiveTraderCloud#500]
I followed the instructions [here](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/docs/setup/docker-setup.md). Services installed and ran correctly but UI stays blank and chrome console shows the following:

...
[INFO][Region-analytics] Region initialised
logger.js:16  [INFO][Region-sidebar] Region initialised
logger.js:16  [INFO][ShellModel] Shell model starting
esp.js:1491 [Router] [ERROR]: Router halted error: [TypeError: this.router.getEventObservable(...).subscribe is not a function]
logger.js:16  [ERROR][UnhandledModelError] Unhandled error in model TypeError: this.router.getEventObservable(...).subscribe is not a function(…)
esp.js:2854 Uncaught TypeError: this.router.getEventObservable(...).subscribe is not a functionvalue @ shellModel.js:51value @ shellModel.js:32(anonymous function) @ esp.js:2768value @ esp.js:4066value @ esp.js:4189i @ esp.js:2683value @ esp.js:2701value @ esp.js:2640value @ esp.js:2524value @ esp.js:2379value @ appBootstrapper.js:151value @ appBootstrapper.js:44(anonymous function) @ appBootstrapper.js:167e @ bootstrap f85143c…:71(anonymous function) @ app.js:5e @ bootstrap f85143c…:71window.webpackJsonp @ bootstrap f85143c…:42(anonymous function) @ app.js:1
logger.js:16  [INFO][Connection] Connected
5logger.js:16  [DEBUG][Connection] Subscribing to topic [status]. Is connected [true]
logger.js:16  [DEBUG][ServiceClient:reference] Will use service instance [reference.a43d] for stream operation [getCurrencyPairUpdatesStream]. IsConnected: [true]
...

**Comment by qooroo** [comment]
We screwed up an npm package upgrade - currently fixing :)

**Comment by sirockin** [comment]
Thanks for the very fast response!

**Comment by sirockin** [comment]
I just retried (removed all docker containers, recreated repostiory as per instructions and ran ./runAll) and got identical result.

**Comment by sirockin** [comment]
Now working on Windows after I wiped all my Docker images :) Thanks again for the quick response.
