### ISSUE TITLE
Local Docker Installation does not work after ./killAll then ./runAll

### ISSUE THREAD

**Issue by sirockin** [AdaptiveConsulting/ReactiveTraderCloud#504]
Unless I've misunderstood, running./killAll after ./runAll should restore the application to its original state. In my case (on Windows) the resulting front end is an empty shell, even after I reboot my machine.

docker ps appears to show all services running ok.

[chrome_console.txt](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/files/427553/chrome_console.txt)
<img width="1076" alt="capture" src="https://cloud.githubusercontent.com/assets/7776773/17818476/088932a4-6644-11e6-822f-3f777a03031f.PNG">

**Comment by tdeheurles** [comment]
The killAll command should kill all reactiveTrader containers. If your browser have already loaded the app, this appearance is normal.

Could you copy/paste a copy of your docker ps please ?

**Comment by sirockin** [comment]
Sorry, I should have clarified, this is what I see after running ./runAll again, and loading the application and refreshing (or hard refreshing) the browser.

docker ps below:

`
Sirockin@Sirockin-PC MINGW64 /c/users/sirockin/source/reactivetradercloud/deploy/docker (master)
$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
1388556a41ab        reactivetrader/servers:0.1      "bash -c 'dotnet run "   16 minutes ago      Up 16 minutes                           analytics
9cc95086c0e1        reactivetrader/servers:0.1      "bash -c 'dotnet run "   16 minutes ago      Up 16 minutes                           blotter
58dcfc8c58d0        reactivetrader/servers:0.1      "bash -c 'dotnet run "   16 minutes ago      Up 16 minutes                           tradeexecution
deb743695ad8        reactivetrader/servers:0.1      "bash -c 'dotnet run "   16 minutes ago      Up 16 minutes                           pricing
f558feb3af00        reactivetrader/servers:0.1      "bash -c 'dotnet run "   16 minutes ago      Up 16 minutes                           reference
4adbebc4fd2e        reactivetrader/broker:0.0       "/bin/sh -c 'crossbar"   16 minutes ago      Up 16 minutes                           broker
5f70a4456924        reactivetrader/eventstore:0.0   "/bin/sh -c './run-no"   16 minutes ago      Up 16 minutes                           eventstore
c40b49031f88        reactivetrader/web:0.0          "bash -c 'cp /localho"   16 minutes ago      Up 16 minutes                           web

Sirockin@Sirockin-PC MINGW64 /c/users/sirockin/source/reactivetradercloud/deploy/docker (master)
`

**Comment by tdeheurles** [comment]
Which process have you gone through to setup the app ?
`Install docker then runAll` or you have `build the containers using the prepare command` ?

**Comment by sirockin** [comment]
Install docker then runAll

**Comment by tdeheurles** [comment]
ok. So please :
- run the `./killAll` command
- control that all containers are stopped
- If not, kill them using the `docker kill` with the container id.
- run the `./runAll` command
- wait something like a minute (depend on your computer)
- control in your browser

**Comment by sirockin** [comment]
That's essentially what I did before. Right now I'm running ./runAll again having wiped existing images using the following commands:
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)

Once I've done that, I'll confirm the application is running properly again then go through those bullet points again and reply with the results.

**Comment by tdeheurles** [comment]
Which kind of docker setup do you have ? 

`docker for windows` or `docker toolbox` ?

**Comment by sirockin** [comment]
I actually have both installed but for this am using docker toolbox. Do you think this could be the issue?

**Comment by tdeheurles** [comment]
No, I just have reproduced.
I'm looking for an explanation.

**Comment by sirockin** [comment]
Okay fine. Let me know if you need any further information. Thanks for responding!

**Comment by sirockin** [comment]
PS wiping images then running ./runAll has restored the application.

**Comment by tdeheurles** [comment]
I have started the differents services with a pause between each and it solved the issue:

```
for server in "web" "eventstore" "broker" "referencedataread" "pricing" "tradeexecution" "blotter" "analytics"
do
    cd run/$server
    ./run $build $release || scream $server
    sleep 5
    cd ../..
done
```

Just added the `sleep 5`.

Without that, the .NET services have some failure when trying to connect to crossbar:

```
2016-08-19 18:21:08 [Error] Connection Failed.
System.AggregateException: One or more errors occurred. (Connection refused 127.0.0.1:8080) ---> System.Net.Internals.SocketExceptionFactory+ExtendedS
ocketException: Connection refused 127.0.0.1:8080
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
```

@qooroo , could you have a look to that please.
@sirockin , thanks for this

**Comment by sirockin** [comment]
@tdeheurles thank you!
