### ISSUE TITLE
Docker build files: '-f' flag in docker tag command causes error

### ISSUE THREAD

**Issue by sirockin** [AdaptiveConsulting/ReactiveTraderCloud#505]
When I run `./prepare build services x` via Docker Quickstart terminal on Windows 10, the console gives me the error `unknown shorthand flag: 'f' in -f`
`see docker tag --help`
 
When I have a closer look I see that the `docker tag` command in each of the /build/{servicename/build.sh folders contains the `-f` flag. The [docker documentation for tag](https://docs.docker.com/engine/reference/commandline/tag/) does not show a `-f` flag. Removing the flag from each build.sh file appears to fix this problem and the images get tagged as expected.

**Comment by tdeheurles** [comment]
Thanks for that @sirockin, it's a docker breaking change. 
We will update that.

**Comment by sirockin** [comment]
No problem, thanks for responding.
