### ISSUE TITLE
web/build.sh fails on windows due to missing npminstall.sh

### ISSUE THREAD

**Issue by sirockin** [AdaptiveConsulting/ReactiveTraderCloud#506]
When I run `.prepare build web 4` from Docker Quickstart Terminal on  Windows, I get the following trace at Step 7:

Step 7 : CMD ./npminstall.sh
 ---> Running in 66b03ffab648
 ---> 5620fe298e06
Removing intermediate container 66b03ffab648
Successfully built 5620fe298e06
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
++ pwd
++ pwd
- docker run -v //c/users/sirockin/source/ReactiveTraderCloud/deploy/docker/build/web/.npm:/.npm -v //c/users/sirockin/source/ReactiveTraderCloud/deploy/docker/build/web/dist:/dist weareadaptive/websrc:4
- MSYS_NO_PATHCONV=1
- docker.exe run -v //c/users/sirockin/source/ReactiveTraderCloud/deploy/docker/build/web/.npm:/.npm -v //c/users/sirockin/source/ReactiveTraderCloud/deploy/docker/build/web/dist:/dist weareadaptive/websrc:4
  /bin/sh: 1: ./npminstall.sh: not found

**Comment by tdeheurles** [comment]
hi.
Could you confirm you did `git clone` with [LF behavior](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/docs/setup/docker-setup.md#clone-the-repository) ?

You can open the file corresponding to [npminstall.sh](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/deploy/docker/build/web/npminstall/npminstall.sh) in your repository and confirm the line ending.
You can use VisualStudio code or Notepad++ to easily have the information.

**Comment by sirockin** [comment]
Hi tdeheurles. 

Yes lines are terminated with CR/LF.

**Comment by tdeheurles** [comment]
Sorry but you need to change that to continue. 
The files are injected in the container and bash don't know how to read the files in CRLF.
There are a lot of files in this case, you should follow the [tutorial](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/docs/setup/docker-setup.md#clone-the-repository) and clone again.

**Comment by sirockin** [comment]
Strange because I can confirm that I did indeed run the command `git config --global core.autocrlf false` before cloning.

**Comment by tdeheurles** [comment]
Git configuration is a pain with the different layer of config.
If it doesn't work second time, try with `git config core.eol lf`.

But be careful with your other project because this is global (no local solution for clone).
You should list your configuration before doing that: `git config -l --show-origin` and make a copy somewhere

**Comment by sirockin** [comment]
Hi @tdeheurles. Cloning again after `git config core.eol lf` did correct the CRLF problem and in turn got rid of that error message, thanks. It fails further down the script now - I'll post a seperate issue on that.

**Comment by tdeheurles** [comment]
You're welcome,
I re-open the issue until the documentation is updated.

**Comment by sirockin** [comment]
Okay, great, thanks again.

**Comment by tdeheurles** [comment]
documentation merged
