### ISSUE TITLE
web/build.sh fails on windows when copying dist

### ISSUE THREAD

**Issue by sirockin** [AdaptiveConsulting/ReactiveTraderCloud#509]
When running in Docker Quickstart Terminal on Windows, web/build.sh fails with a console output that ends with the following:

```
Child extract-text-webpack-plugin:
        + 9 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
saving cache ...
copying dist ...
cp: cannot stat ‘./dist’: No such file or directory

Sirockin@Sirockin-PC MINGW64 /c/users/sirockin/source/ReactiveFlowCloud/deploy/docker (master)
$
```

**Comment by tdeheurles** [comment]
Dist is a shared folder between your host and a container.
The idea is the container build the web output and then the script can continue with the content inside.

This code in web/build.sh:
```
docker run              \
  -v /$(pwd)/.npm:/.npm \
  -v /$(pwd)/dist:/dist \
  weareadaptive/websrc:$build
```
should at least have created the folder ...

Can I have your docker version please ?

**Comment by sirockin** [comment]
`$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
`

**Comment by tdeheurles** [comment]
I builld with the same version. It's not that.

Can you show me the exact command you used to build please ?

**Comment by sirockin** [comment]
`./prepare build web 5`

(from the docker/deploy folder). FYI, the command takes ages (over 30 minutes) to run to this point. My initial suspicions were that the copy process was dying because I was running out of disk space but I have around 20GB free.

**Comment by sirockin** [comment]
Also FYI I can build and run the client fine from the client folder using `npm install` and `npm start` .

**Comment by tdeheurles** [comment]
`npm` is not matching very well with `docker` when we use host sharing.
There are so much connections and files updated that `often` this part of the build break.

To work around this issue and the fact some of our code is running on the host (some of the bash scripts), we have developed a [tool](https://github.com/tdeheurles/hive) that is used in a [branch of ReactiveTrader](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/tree/hive-deployment).

This tool is really RnD at the moment and you should give an eye only if you're interested in the docker utilization in this project. If not, you should try again to build with deploy/docker/prepare or continue with the UI in local development.

**Comment by sirockin** [comment]
Thanks Thibault. We are definitely interested in docker deployment so I'll keep an eye on that branch.

**Comment by tdeheurles** [comment]
linked to https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/574

**Comment by tdeheurles** [comment]
fix merged
