### ISSUE TITLE
'Return' icon not visible in browser (GBPJPY)

### ISSUE THREAD

**Issue by ferguskeenan** [AdaptiveConsulting/ReactiveTraderCloud#516]
![missing return icon](https://cloud.githubusercontent.com/assets/8998351/19221688/4d458cc0-8e40-11e6-89a1-4458c86b986b.PNG)

Icon is visible when tile is popped out
![visible return icon](https://cloud.githubusercontent.com/assets/8998351/19221697/58f0c29c-8e40-11e6-8f51-b8a91c1828eb.PNG)

**Comment by zeala** [comment]
Looks like this issues has been resolved. closing
