### ISSUE TITLE
When the analysis panel is popped out, the chart tooltip appears in the main app

### ISSUE THREAD

**Issue by ferguskeenan** [AdaptiveConsulting/ReactiveTraderCloud#518]
<img width="670" alt="chart tooltip" src="https://cloud.githubusercontent.com/assets/8998351/19351842/45bbdff0-9155-11e6-9518-d14c66c0f956.PNG">

**Comment by amilanan** [comment]
Seems to be resolved.

**Comment by amilanan** [comment]
Steps to reproduce:
1. Open RTC with desktop app
2. Detach the analysis panel and hover the chart

Result: Tool tip is showing over the main panel (far left corner)

**Comment by keshaldesai** [comment]
The bug isn't isolated to the desktop and occurs without detaching. I'm getting this on the rtc site:

![chart-bug](https://user-images.githubusercontent.com/32776407/41366455-24b29a8a-6f0a-11e8-93d3-41209cfe9ea5.PNG)
![chart-bug2](https://user-images.githubusercontent.com/32776407/41366454-249d6d86-6f0a-11e8-815a-d4fb7bdab291.PNG)

The frequency increases when I click the chart and move my mouse out.

**Comment by mbehery85** [comment]
This has been tested against the latest release and the reported issue in regards to the detaching and values being left behind are now longer present and resolved.

Thanks
