### ISSUE TITLE
Missing files in build...

### ISSUE THREAD

**Issue by hazinstore** [AdaptiveConsulting/ReactiveTraderCloud#519]
Following directions from here....
https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/docs/setup/linux-setup.md
But when I do dotnet restore I get the following error...

```
dotnet restore
/usr/share/dotnet/sdk/1.0.0-preview4-004079/NuGet.targets(164,5): error MSB3202: The project file "/home/user/Projects/ReactiveTraderCloud/src/server/Adaptive.ReactiveTrader.Server.Pricing/Adaptive.ReactiveTrader.Server.Pricing.xproj.metaproj" was not found. [/home/user/Projects/ReactiveTraderCloud/src/server/Adaptive.ReactiveTrader.Server.sln]
```

Same is true for all .metaproj files.  Not sure if those are generated or just missing.

**Comment by hazinstore** [comment]
Also the .sln files don't open properly in monodevelop, what IDE are you guys using?

**Comment by raybooysen** [comment]
@hazinstore thanks for the issue, we're having a look

**Comment by tdeheurles** [comment]
@qiming @maciejAdaptive is this still relevant or I can close as we are not using this dotnet anymore ?

**Comment by MaciejAdaptive** [comment]
The original issue may be fixed, but I'm concerned about issue raised by @hazinstore - I haven't tried opening solution in monodev (BTW: I'm using VS 2017 Community Edition (free)).

I would: 
1. Close original issue as non-relevant
2. Try opening solution in monodev, if problem still occurs - create a new issue

Are you able to do it @tdeheurles  ?

**Comment by MaciejAdaptive** [comment]
According to http://www.monodevelop.com/download/ monodev is bundled in Xamarin. Using latest download, I was not able to open solution in Xamarin IDE. @hazinstore - which OS are you using?
