### ISSUE TITLE
Tiles gets stuck in 'Executing' state when rejected by Limit Checker

### ISSUE THREAD

**Issue by ferguskeenan** [AdaptiveConsulting/ReactiveTraderCloud#522]
<img width="473" alt="reject trades stuck executing" src="https://cloud.githubusercontent.com/assets/8998351/20679766/32757ec0-b594-11e6-9320-807017719ba1.PNG">

**Comment by fdore** [comment]
This bug only happens with version 6 of openfin. Will raise a PR to handle that scenario more gracefully. Another issue I noticed (probably related) is that RTC doesn't get notified when the LimitChecker app is closed, which means we continue sending trades to the LimitChecker despite it being closed (causing future trades to be rejected).

**Comment by fdore** [comment]
Inter application communication is only possible between two apps using the same runtime. So we will need to upgrade the limit checker app to use the v6 .NET adapter.
