### ISSUE TITLE
Port the client side transport to .NET (PCL)

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#53]
This is the first step to get the WPF and Xamarin (iOS, Android, iWatch) versions ported across.

You should probably port the WPF client across when you do that, to make sure this is working. We don't expect the WPF client to support all the failure scenarios (it should just work with happy paths).

**Comment by ferguskeenan** [comment]
@jonclare - what is the status of this now?
