### ISSUE TITLE
Tile position not restored?

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#532]
Reported by Steve at OpenFin:

>  If I close and re-open the application with tiles torn out ... the app will restart with the tiles torn out but not in the proper location

**Comment by odeheurles** [comment]
I believe we name the child windows something like "CCY-EURUSD" and OpenFin automatically stores the position of the tile and restore it at the same place based on its name. Is that a change with runtime 6 or a regression on our side?

@fdore could you please have a look when you have a chance?

**Comment by fdore** [comment]
I'm able to reproduce the issue with version 6 of the runtime. When using version 5, the tiles open in the right position.

You can download RTC with version 5 of the runtime with this link:
https://install.openfin.co/download?fileName=RTC-5.44.11.10&config=https://raw.githubusercontent.com/AdaptiveConsulting/ReactiveTraderCloud/30d8e83e26ab330a7f983ff6ad1ccca129d88381/src/client/config/openfin/demo.app.json

**Comment by ferguskeenan** [comment]
But we have deployed version 6 as our Prod version - is there a way to fix in this version? Or something we as OpenFin to investigate?

**Comment by fdore** [comment]
Before raising that with OpenFin, I will try with the latest runtime version..

**Comment by fdore** [comment]
The issue seems to have been resolved in version 6.49.16.16
