### ISSUE TITLE
Update .NET Core tooling

### ISSUE THREAD

**Issue by qooroo** [AdaptiveConsulting/ReactiveTraderCloud#536]
VS2017 RTMs on March 7th, we should update build files by then (project.json => csproj)

Currently WIP with rc4 tooling on branch `vs2017`:

- [x] Migrate project.json to csproj
- [x] Update Docker build files
- [ ] Update test runner

**Comment by carlosrfernandez** [comment]
Does the xamarin folder need to have the nugets in there? I think we can add that to .gitignore.

**Comment by tdeheurles** [comment]
@carlosrfernandez @qooroo is this fixed by https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/589 ?

**Comment by qooroo** [comment]
Yes!
