### ISSUE TITLE
Debugging client from Visual Studio 2015

### ISSUE THREAD

**Issue by datasmithtech** [AdaptiveConsulting/ReactiveTraderCloud#540]
I downloaded the zip
I opened the client source as a web site using Visual Studio 2015..
I install webpack task runner.
I opened task explorer
re-ordered paths of external tools, so that run development looks good

I could not run in VS 2015 debugger, nor debug the emitted code from webpack

are there any easy changes to project so that this can be debugged using VS 2015?

**Comment by tdeheurles** [comment]
@maciejAdaptive @qiming, are we still concerned for this as we are miving to vs2017 ?

**Comment by MaciejAdaptive** [comment]
I would close it, what do you think @qooroo ?

**Comment by qooroo** [comment]
Yeah, none of our front-end dev processes uses VS to debug.
