### ISSUE TITLE
Event Store deployment for BCN talk

### ISSUE THREAD

**Issue by daniel-smith** [AdaptiveConsulting/ReactiveTraderCloud#553]
As part of an upcoming talk @mattbarrett and I are doing in BCN on 13 June, we need to make some changes to the event store deployment. This relates to the code changes for #550, which are on the [process](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/tree/process) branch. See changes at https://github.com/AdaptiveConsulting/ReactiveTraderCloud/compare/master...process.

1. Deploy EventStore version 4.0.1
2. Ensure projections are running at start up, along with standard projections. This is done via the command line args `--run-projections=all` and `--start-standard-projections=true` (see [here](http://docs.geteventstore.com/introduction/4.0.0/setup_projections/))
3. Add new projection by running the following curl command:

~~~~
body=$(cat << EOF
fromStreams(["\$ce-trade", "\$ce-creditAccount"])
    .when({
        TradeCreatedEvent: function (s, e) {
            linkTo("trade_execution", e);
        },
        CreditReservedEvent: function (s, e) {
            linkTo("trade_execution", e);
        },
        CreditLimitBreachedEvent: function (s, e) {
            linkTo("trade_execution", e);
        },
        TradeCompletedEvent: function (s, e) {
            linkTo("trade_execution", e);
        },
        TradeRejectedEvent: function (s, e) {
            linkTo("trade_execution", e);
        }
    });
EOF
)

curl -X POST -i "http://localhost:2113/projections/continuous?name=trade_execution_proj&type=JS&enabled=true&emit=true&trackemittedstreams=true" -u admin:changeit -H "Content-Type: application/json" -d "$body"
~~~~

4. Add a persistent subscription with the following curl command:

~~~~
curl -X PUT -i "http://localhost:2113/subscriptions/trade_execution/trade_execution_group" -u admin:changeit -H "Content-Type: application/json" -d '{ "resolveLinktos": true }'
~~~~

**Comment by tdeheurles** [comment]
@daniel-smith where are we with this one please ? To me it can be closed no ?

**Comment by daniel-smith** [comment]
It would be good to look at merging the process branch to master, before we close this issue.

**Comment by zeala** [comment]
We have #550 to keep track of the work on the process branch/merging to master.  
Agreed to close this issue.
