### ISSUE TITLE
not working out of the box

### ISSUE THREAD

**Issue by joyanta** [AdaptiveConsulting/ReactiveTraderCloud#557]
Hi, 
Apologies upfront (if this is an pre existing issue or if I am doing something wrong - which is most likely). 

I clone the repo, and then it is a matter of pointing to the launcher project and start it. 

Sure i get the process running but they all have a lot of error messages.

I assumed you have some kind of mock data underneath so that one has a ready solution but I presume that might not be the case.

there are some instructions, but I am unsure if that fixes any of that.

previously I am sure this or the ReactiveTrader solution worked out of the box.

**Comment by qooroo** [comment]
Hi @joyanta, thanks for reporting this.

We are aware of this issue and will work to get a version with VS2017 working soon (.NET Core with msbuild)

**Comment by joyanta** [comment]
hi cheers...
because I was sure it was working (an earlier vision of it)

**Comment by joyanta** [comment]
wonder if works on VS2017. I guess i could try at my end.
