### ISSUE TITLE
Devops Improvements

### ISSUE THREAD

**Issue by qooroo** [AdaptiveConsulting/ReactiveTraderCloud#558]
- [x] 404 handling from nsgate
- [x] Access to Event Store web console via nsgate

**Comment by tdeheurles** [comment]
linked to https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/574

**Comment by tdeheurles** [comment]
404 is handled for http but not https

**Comment by tdeheurles** [comment]
Eventstore is accessible in this pattern:
- http://eventstore-demo.adaptivecluster.com:2113

But *https* is not redirecting well:
- https://eventstore-demo.adaptivecluster.com:2113

**Comment by tdeheurles** [comment]
https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/602
