### ISSUE TITLE
Code documentation || learning resources

### ISSUE THREAD

**Issue by obeyda** [AdaptiveConsulting/ReactiveTraderCloud#614]
#### This isn't really an issue, this is just a request

I am trying to learn how to build microservices with CQRS, ES, reactive programming and messaging, I have a good understanding of the theoretical part but there isn't much **hands-on** examples about this subject.
Reactive Trader Cloud is the most complete app that I could find which implements all these concepts **(and much more)**, I am trying to dive into the code to understand its ins and outs, however I would really appreciate having some code documentation to help.
Also, having more learning resources and/or examples would be really helpful. 

---
This app is nice, if this is a demo showcasing app, I am wondering how an enterprise reactive cqrs/es microservices architecture would be... nice work!

**Comment by mattgi** [comment]
Definitely agree with this sentiment.. things like auth. samples / guidance and general documentation would make this reference implementation hard to beat. But in its current form, its a lot of information and code to wade through.
