### ISSUE TITLE
Improve environment creation time

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#62]
Test 
- when using docker hub
- when using a docker repo in the same gcloud datacenter

2 levels of nginx might be a better setup than using the google load balancer stuff (slow to setup)

**Comment by tdeheurles** [comment]
- we have 2 level of nginx
- gcloud have a hub.docker cache that make the download really fast
Moving to a local registry doesn t seems to add any value
