### ISSUE TITLE
Redux state and actions are mutated in some of the reducers

### ISSUE THREAD

**Issue by silviuadaptive** [AdaptiveConsulting/ReactiveTraderCloud#625]
This can cause some performance issues and weird bugs that are hard to debug.

Would be necessary to check all reducers and see which ones mutates the original state. 

In addition consider adding a middleware that throws errors on state mutations, to avoid from happening again. https://github.com/leoasis/redux-immutable-state-invariant or https://github.com/buunguyen/redux-freeze (middleware is added in https://github.com/AdaptiveConsulting/ReactiveTraderCloud/issues/629)

Example of state mutation:

![image](https://user-images.githubusercontent.com/35812387/35505047-b816f82c-04dc-11e8-8d7b-7479c3669ede.png)

Example of action mutation from src/client/src/ui/spotTile/spotTileOperations.ts:

![image](https://user-images.githubusercontent.com/35812387/35676408-9a091860-0743-11e8-9a4c-ce5ce1b5234e.png)

**Comment by zeala** [comment]
fixed
