### ISSUE TITLE
Consider normalising spotTile state and use a selector

### ISSUE THREAD

**Issue by silviuadaptive** [AdaptiveConsulting/ReactiveTraderCloud#626]
For example spotTiles has data that is also present in the pricingService, therefore would be beneficial to have that data in only one place. 

The main benefit is that if you were to create a new action that updates the price, you only need to add a single reducer, instead of adding in 2 places. For example if is only added to `pricingService` reducer, the `spotTiles` data would be out of sync.

A suggestion would be to add a selector that creates the `spotTile` data from `spotTiles` and `pricingService`.

spotTiles data:

![image](https://user-images.githubusercontent.com/35812387/35507209-e9c67bd4-04e3-11e8-8265-9f198c32aebe.png)

pricingService data:

![image](https://user-images.githubusercontent.com/35812387/35507187-d928ad10-04e3-11e8-8d53-ed5b77cf1c55.png)

You can see that many of the keys (mid, ratePrecision, currencyPaid, symbol, bid, ask, valueDate) are duplicated.

https://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html

**Comment by zeala** [comment]
the state is flattened, reference data stored and referenced from the single source.
closing
