### ISSUE TITLE
Make RXJS code more readable and easier to follow/debug

### ISSUE THREAD

**Issue by silviuadaptive** [AdaptiveConsulting/ReactiveTraderCloud#629]
Files that might need some work:

 - src/client/src/system/service/serviceClient.ts
 - src/client/src/services/referenceDataService.ts
 - src/client/src/services/blotterService.ts
 - src/client/src/system/service/serviceObservableExtensions.ts

Other stuff to do:

 - Add comments to explain a bit what the epics do. For example `referenceServiceEpic` is not clear what is doing except dispatching an init type action.
 - https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/627#discussion_r164693080

**Comment by zeala** [comment]
@silviuadaptive - this is a bit too generic and needs a discussion. Re comments in the code -  the code should be self-documented. We don't keep comments in the code as a rule with some exceptions of implementing unclear workarounds.

I suggest splitting this issue into documenting the streaming services in a Confluence page and a separate one for improving typings in the code.

I am closing this issue.

**Comment by zeala** [comment]
Re-opening the issue after clarifying the requirements.

**Comment by dwalker11** [comment]
Hey @zeala, out of curiosity do we have any documentation on the overall architecture of this application?

**Comment by zeala** [comment]
closing as fixed
