### ISSUE TITLE
Firefox- UI issue - internal scroll bar appears in firefox

### ISSUE THREAD

**Issue by amilanan** [AdaptiveConsulting/ReactiveTraderCloud#647]
There is a scrollbar as part of the UI. See the attachment.
![2018-02-06 15_07_59-photos](https://user-images.githubusercontent.com/24304223/35881864-38532f96-0b50-11e8-9ba6-4a7a8eedf6e2.png)

**Comment by keshaldesai** [comment]
The relevant scrollbar appears in Chrome and Safari as well. In those browsers, it is styled. In Firefox, it appears the way it does because [Firefox does not support custom CSS for scrollbars](https://bugzilla.mozilla.org/show_bug.cgi?id=77790).

**Comment by zeala** [comment]
closing, as this issue is browser-dependant
