### ISSUE TITLE
Establish a consistent convention and directory structure

### ISSUE THREAD

**Issue by dwalker11** [AdaptiveConsulting/ReactiveTraderCloud#663]
The current state of the client source code lacks a consistent style and a convention for describing the overall architecture of the web UI. This issue aims to resolve some of these issues by establishing a consistent convention and folder structure.

**Comment by dwalker11** [comment]
The first issues focused mainly on the ui components, but this could expand to all files under 'src'.
The goal is to move towards a more fractal design. (ie. Feature-based vs Function-based)

Links:
- https://hackernoon.com/fractal-a-react-app-structure-for-infinite-scale-4dab943092af
- ‎https://medium.com/styled-components/component-folder-pattern-ee42df37ec68
- ‎https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure

**Comment by dwalker11** [comment]
![reactive trader tree](https://user-images.githubusercontent.com/2473849/36549738-7ea45448-17c1-11e8-8193-b6e48cd54840.png)

**Comment by dwalker11** [comment]
https://docs.google.com/drawings/d/1KzfGClfqM41AaSB9sSx9nUEb8eJ-JBU5gi2DlweNTH4/edit

**Comment by dwalker11** [comment]
Every component has its own folder, which houses all files that pertain to the component in question. At the minimum, the folder contains an index file, a view file, and a container file (if necessary). Component files and folders are camel-cased with the folders being capitalized. Component folders have one default export, which is container or view file if a container file is not present.

Container components (or components that interact with the store) sit at the root of the UI folder. Alternatively, we could nest the folders in the same pattern of the rendered component tree.

Presentation components live as subcomponents under their respective parent component, which is ultimately a container component. Presentation components can be composable and model the component hierarchy.

Reusable components live under a root 'commons' directory.

Actions, Epics, and Reducer live in an "Operations" file that sits at the root of a container folder; following the ducks' pattern (*see links below).  Alternatively, we could implement the re-ducks pattern (*see links below)
Links:
- https://github.com/erikras/ducks-modular-redux
- https://github.com/alexnm/re-ducks

**Comment by bhavesh-desai-scratch** [comment]
No longer relevant
