### ISSUE TITLE
Confirmation message amount is formatted incorrectly

### ISSUE THREAD

**Issue by amilanan** [AdaptiveConsulting/ReactiveTraderCloud#669]
Steps:
1. Set amount with 6 digits or more
2. Click buy or sell
3.Check the message

Result:  The amount is not formatted correctly, delimiting commas are missing.
![2018-02-22 13_50_53-commas-reactive trader cloud](https://user-images.githubusercontent.com/24304223/36558239-6a5eec2a-17d8-11e8-9d78-9e612a8b7ef1.png)

Expected: Displayed amount should have delimiting commas in all amount figures

**Comment by zeala** [comment]
fixed
