### ISSUE TITLE
Spot date is wrong on the tail and on the message

### ISSUE THREAD

**Issue by amilanan** [AdaptiveConsulting/ReactiveTraderCloud#688]
The spot date should be offset by 2 days.
On the tail hoover event shows +1 day
On message notification message shows +3 days.
Also the formatting is not consistent - the format should be SP .01 MAR.
![image 1](https://user-images.githubusercontent.com/24304223/36849804-ffb46502-1d32-11e8-9fd1-a25fede1216e.png)
![image](https://user-images.githubusercontent.com/24304223/36849805-ffc9ae6c-1d32-11e8-8e1e-ae6626f676d2.png)

**Comment by jem77** [comment]
Incorrect spot date on spot tile is a server side issue: class MeanReversionRandomWalkPriceGenerator calculates the spot date as T+2 including weekends. To fix update code to  ValueDate should be: 
ValueDate = DateTime.UtcNow.AddDays(2).Date.ToWeekday(),

**Comment by jem77** [comment]
Inconsistency of the tail hoover event showing T+1, notification T+3 and blotter inconsistency for spot date is an issue only present in New York as London correctly shows the provided server side date of T+2 (albeit including weekends). This is a timezone issue and I will push a fix for this

**Comment by amilanan** [comment]
Consistency issue is resolved.
