### ISSUE TITLE
[OpenFin version] Undocking and close icon overlap

### ISSUE THREAD

**Issue by amilanan** [AdaptiveConsulting/ReactiveTraderCloud#690]
To reproduce: 

1.  Pop out at least two tiles 
2.  Move them alongside each other, they should dock and the 
3. new control to undock them will appear on hover-over
![2018-03-01 14_21_03-reactive trader cloud](https://user-images.githubusercontent.com/24304223/36864982-3ae580ec-1d5c-11e8-9c82-08c86a275004.png)

**Comment by zeala** [comment]
fixed
