### ISSUE TITLE
[IE] Grid Filter Issues 

### ISSUE THREAD

**Issue by amilanan** [AdaptiveConsulting/ReactiveTraderCloud#706]
1. When focus is on the free text filter - there are 2 close icons overlapping (attach1)
![filter focus - reactive trader cloud - internet explorer](https://user-images.githubusercontent.com/24304223/37422223-2332d64a-2791-11e8-9578-7b71a11bac48.png)

2. Column filters have 2 arrows for the drop-down selectio(attach2) 
![dds - reactive trader cloud - internet explorer](https://user-images.githubusercontent.com/24304223/37422495-9cf38b46-2791-11e8-98cc-9b2ef68d760f.png)

3. [IE and Edge] ]Date Filter is missing a calendar selection option and basically does not work(attach3) 
![calendar - internet explorer](https://user-images.githubusercontent.com/24304223/37422609-ed8b22b2-2791-11e8-8f82-25c6386216aa.png)
4. Rate filter EQUALS does not work 
![rate-reactive trader cloud - internet explorer](https://user-images.githubusercontent.com/24304223/37422828-8becad72-2792-11e8-82f4-86a3feff3e08.png)

**Comment by mbehery85** [comment]
This has been tested against the latest release and the reported issued does not seem to be resolved across all the filters available in the blotter.

Thanks
