### ISSUE TITLE
[Chrome] Grid Filter Issues

### ISSUE THREAD

**Issue by amilanan** [AdaptiveConsulting/ReactiveTraderCloud#707]
1. Filter scroll on Dropdown list check box is showing above the border line 
![filterscrollddl-reactive trader cloud](https://user-images.githubusercontent.com/24304223/37426386-a4c6551e-279c-11e8-9613-b9cdbc5a90c2.png)

2. Date filter is missing the month abbreviation 
![datefiltercalendar-reactive trader cloud](https://user-images.githubusercontent.com/24304223/37426416-bc2b35bc-279c-11e8-8d49-34e182c512d0.png)

**Comment by mbehery85** [comment]
This has been tested against the latest release and the reported issued does not seem to be resolved across all the filters available in the blotter.

Thanks
