### ISSUE TITLE
ChartIQ endpoint broken

### ISSUE THREAD

**Issue by keshaldesai** [AdaptiveConsulting/ReactiveTraderCloud#737]
Currently our application points to [http://adaptiveconsulting.github.io/ReactiveTraderCloud/chartiq/chartiq-shim.html](http://adaptiveconsulting.github.io/ReactiveTraderCloud/chartiq/chartiq-shim.html) for ChartIQ functionality. This link does not currently work. Without this endpoint, the ChartIQ popout will silently fail.

The link is used as such: `http://adaptiveconsulting.github.io/ReactiveTraderCloud/chartiq/chartiq-shim.html?symbol=${symbol}&period=${interval}`

**Comment by tcdev00** [comment]
The endpoint was fallen because there was no branch gh-pages and the configuration for Github Pages was disabled.
It's been fixed by re-pushing the branch gh-pages, enabling Github Pages in configuration and setting "gh-pages" branch as source.
