### ISSUE TITLE
Implement WebSocket fallback

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#82]
- [x]  implement fallback in the UI
- [x] update connection status when using long polling in the UI
- [ ] @tdeheurles : configure nginx routing

**Comment by ferguskeenan** [comment]
Related to #221

**Comment by fdore** [comment]
Currently getting the following error when disabling websocket on the client:
XMLHttpRequest cannot load http://web-dev.adaptivecluster.com:8080/lp/open. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://web-dev.adaptivecluster.com' is therefore not allowed access. The response had HTTP status code 501.

**Comment by tdeheurles** [comment]
fixed by nsgate 0.2.27
