### ISSUE TITLE
Frontend support for WSS

### ISSUE THREAD

**Issue by odeheurles** [AdaptiveConsulting/ReactiveTraderCloud#83]
When running under https, the client should connect to /wws, not /ws

http 80
ws 8080

https 443
wws 443

**Comment by KeithWoods** [comment]
@odeheurles  I don't believe this is done. Adding to our next milestone

**Comment by tdeheurles** [comment]
Nginx was prepared in dev. I will have to add some code to the master branch.

**Comment by KeithWoods** [comment]
@tdeheurles do you have an idea of the status of this?

**Comment by tdeheurles** [comment]
I have no idea for the client.
nginx is setup for wss. But it's not tested for now.
