### ISSUE TITLE
"Displaying rows X of Y" is incorrect

### ISSUE THREAD

**Issue by mozmorris** [AdaptiveConsulting/ReactiveTraderCloud#945]
![image](https://user-images.githubusercontent.com/156303/51609025-f6ad4880-1f10-11e9-8755-1170ad98d7e2.png)

**Comment by mbehery85** [comment]
This is has been checked against the latest release and the X of Y count does seem to be correct.

However looking at the screen shot attached does seem that the green strips on the left may have caused confusion.

The green strips are reflecting the Done status for the orders whereas on the right hand side shows the scrollbar to go through the filtered list (attached are examples).

Thanks
![XofYCountCorrectlyDisplayed](https://user-images.githubusercontent.com/52500378/62298311-b3590700-b46a-11e9-8823-0cb594eba1f1.PNG)
![XofYCountCorrectlyDisplayed_1](https://user-images.githubusercontent.com/52500378/62298312-b3590700-b46a-11e9-9be5-c551a5622b2d.PNG)
![XofYCountCorrectlyDisplayed_2](https://user-images.githubusercontent.com/52500378/62298313-b3590700-b46a-11e9-91f5-68518f7b5c4d.PNG)
